version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: elasticsearch_crawler
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - crawler_network
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  postgres:
    image: postgres:14
    container_name: postgres_crawler
    environment:
      POSTGRES_USER: crawler_user
      POSTGRES_PASSWORD: crawler_pass
      POSTGRES_DB: crawler_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - crawler_network

networks:
  crawler_network:
    driver: bridge

volumes:
  postgres_data:
  elasticsearch_data:
